export {
  getActiveBotWsReplyHandle,
  getAccountRuntime,
  getAccountRuntimeSnapshot,
  getBotWsPushHandle,
  getWecomRuntime,
  getWecomRuntimeConfig,
  registerActiveBotWsReplyHandle,
  registerAccountRuntime,
  registerBotWsPushHandle,
  setWecomRuntime,
  unregisterActiveBotWsReplyHandle,
  unregisterBotWsPushHandle,
  unregisterAccountRuntime,
} from "./app/index.js";
