import { MESSAGE_BYTE_LIMITS } from "../types/constants.js";

export const LIMITS = {
  STREAM_TTL_MS: 10 * 60 * 1000,
  ACTIVE_REPLY_TTL_MS: 60 * 60 * 1000,
  DEFAULT_DEBOUNCE_MS: 500,
  STREAM_MAX_BYTES: MESSAGE_BYTE_LIMITS.BOT_WS_STREAM,
  REQUEST_TIMEOUT_MS: 15_000,
};
